version: '3.1'
services:
  db:
    image: mysql
    container_name: personapi
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - person_data:/var/lib/mysql
volumes:
  person_data: